### ISSUE TITLE
Allow people with emails from private post-secondary institutions in BC to create Pressbooks accounts

### ISSUE THREAD

**Issue by josieg** [BCcampus/bc-validate#2]
Please add these email domains as accepted emails for creating an account on pressbooks.bccampus.ca and add the schools to the drop-down list on the sign up page:

Acsenda School of Managment - @acsenda.com
Alexander College - @alexandercollege.ca
Columbia College - @columbiacollege.ca
Coquitlam College - @coquitlamcollege.com
Corpus Christi College - @corpuschristi.ca
Eaton College - @etoncollege.ca
Fraser International College - @fraseric.ca
LaSalle College Vancouver - @lasallecollegevancouver.com
Native Education College - @necvancouver.org
Pacific Coast University for Workplace Health Sciences- @pcu-whs.ca
Quest University Canada - @questu.ca
Trinity Western University - @twu.ca
University Canada West - @ucanwest.ca

**Comment by bdolor** [comment]
resolved via https://github.com/BCcampus/bc-validate/commit/886e49f0e31810347bb7cf05db423d0f0949219d

**Comment by bdolor** [comment]
closing https://github.com/BCcampus/bc-validate/releases/tag/1.0.2
