### ISSUE TITLE
Email domains to add :)

### ISSUE THREAD

**Issue by josieg** [BCcampus/bc-validate#6]
Please add these email domains as accepted emails for creating an account on pressbooks.bccampus.ca and add the schools to the drop-down list on the [sign up page](https://pressbooks.bccampus.ca/wp-signup.php):

Adler University - @adler.edu
Fairleigh Dickinson University - @fdu.edu
Yorkville University - @yorkvilleu.ca

Related question, there seems to be a setting for PB Admin to manage this kind of thing, but there are no emails listed there. Maybe this plugin isn't really needed anymore? Not sure. Screenshot below:

![Email domain](https://user-images.githubusercontent.com/23706762/106823171-50cf6100-6635-11eb-8aa2-2ec2f6f1fd29.jpg)

**Comment by alex-418** [comment]
Looking at this one now @josieg ... that new setting looks promising! Will test it out and see if we can migrate our whitelist to this setting, would love to ditch this plugin and give you the ability to manage this list yourself! I'll let you know how it goes.

**Comment by alex-418** [comment]
@josieg Tested the feature and it works well. I've disabled the plugin and moved the whitelist to the settings. Can you please test and let me know if there's any issues?

![whitelist](https://user-images.githubusercontent.com/17072191/108141025-cdbbfb00-7077-11eb-96de-f906b5b7bd86.png)

**Comment by josieg** [comment]
It works! Thanks Alex :)

**Comment by alex-418** [comment]
Glad to hear @josieg feel free to open this issue back up if you encounter any problems.
